---
#tasks file for nfs_client
- name: install nfs package
  yum:
    name: nfs-utils
    state: latest

- name: mount the nfs server to local system at /mnt
  mount:
    path: /mnt
    src: 'managed2:/share'
    fstype: nfs
    state: mounted

